[tool.poetry]
name = "superjumper"
version = "0.1.0"
description = ""
authors = ["zhaojinbiao <zhaojinbiao@zhicui.com.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
